name: PerPlayerChatFilter
main: net.cazzar.bukkit.perplayerchatfilter.PerPlayerChatFilter
version: '1.0.0'
author: cazzar
description: 'Filter the chat per player!'
depend: [ProtocolLib]
commands:
    filterme:
        description: 'control the censor system'
        usage: '/filterme <add|remove> <word...>'